os: linux

language: python

python:
    - 3.7

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4
  
before_install:
    - pip install poetry

install:
    - poetry install -v
    - pip install codecov

before_script:
    - psql -c "CREATE DATABASE roax_postgis;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -d roax_postgis -U postgres

script:
    - pytest --cov=roax --cov-report=xml tests/

after_success:
    - codecov
